.travis.yml
ci/test-ansi.lisp
ci/test-cffi.lisp
ci/test-cl+ssl.lisp

Add some basic Travis CI for commits.

Travis CI artifacts

---

.travis.yml
ci/asdf-finds-abcl.bash
ci/install-adoptjdk.bash
ci/install-jenv.bash
ci/sync-ansi-test.bash
ci/test-ansi.lisp
ci/test-cffi.lisp
ci/test-cl+ssl.lisp

Downloading the AdoptJDK image using via `jenv` in a 2x2 build matrix.

Incomplete work on the CI using AdoptJDK

---

.travis.yml
build.xml
ci/test-abcl.lisp
test/lisp/abcl/jar-pathname.lisp

Fix building from release source archives due to missing Netbeans artifacts.

Easye/releng 1.6.0

---

abcl.asd
test/lisp/cl-bench/wrapper.lisp

New location for CL-BENCH which now contains an ASDF definition.

Overhaul CL-BENCH invocation mechanism

---

t/byte-vectors.lisp

(pfdietz)
<https://github.com/armedbear/abcl/issues/230>

Test for STABLE-SORT on a empty vector

---

src/org/armedbear/lisp/Java.java

TODO: viewing the contents of the primitive array conveniently in
SLIME.

JCLASS now works on primitive arrays

---

README
doc/manual/abcl.tex

Fix some formatting and reference problems.

manual: reverse order of prefaces

---

contrib/abcl-introspect/util.lisp

The integer can be passed meaningfully by passed to syscalls like
fdopen().
TODO: implement in the core application, current strategy needs JSS to
reliably finad access private member fields

abcl-introspect: EXT:STREAM-UNIX-FD returns integer file descriptor

---

src/org/armedbear/lisp/Java.java
t/java-arrays.lisp

Easye/jarray new/20200925b

---

src/org/armedbear/lisp/precompiler.lisp

Fixes <https://abcl.org/trac/ticket/474>.

precompiler: be more careful in optimizing lambda precompilation

---

src/org/armedbear/lisp/util/RandomAccessCharacterFile.java

Using FILE-POSITION to rewind streams that had advanced past the EOF
was throwing internal Java exceptions.
Fixes <https://abcl.org/trac/ticket/473>.

Reset file charset decoder before conversion

---

src/org/armedbear/lisp/fdefinition.lisp

Unfortunately, SLIME v2.26 code can throw errors when compiling Emacs
buffers, namely the pathname may have a device containing the string
"emacs-buffer" whose PATHNAME name denotes the buffer which often
contain wild-pathname characters (e.g. "*slime-scratch*") causing a
naieve PROBE-FILE to throw errors.
TODO redo ABCL SLIME's use of PATHNAME-DEVICE components to mark a
source location.
Use IGNORE-ERRORS to be extra careful.

Ensure that SYS:CHECK-REDEFINITION does not signal error conditions

---

src/org/armedbear/lisp/clos.lisp

This doesn't seem to entirely work.  Need a better test?
Attempts to address <https://github.com/armedbear/abcl/issues/301>

Always define CALL-NEXT-METHOD and NEXT-METHOD-P as local functions

---

CHANGES
README
abcl.asd
abcl.rdf
contrib/abcl-asdf/abcl-asdf-tests.asd
contrib/abcl-asdf/abcl-asdf.asd
contrib/abcl-asdf/asdf-mvn-module.asd
contrib/abcl-introspect/abcl-introspect-test.asd
contrib/abcl-introspect/abcl-introspect.asd
contrib/asdf-jar/asdf-jar.asd
contrib/jfli/README
contrib/jfli/jfli.asd
contrib/jss/jss.asd
contrib/mvn/jna.asd
contrib/pom.xml
doc/design/pathnames/abcl-pathname.org
doc/manual/abcl.bib
doc/manual/abcl.tex
doc/manual/extensions.tex
doc/manual/java.tex
doc/manual/system.tex
doc/manual/threads.tex
doc/releng.org
pom.xml
src/org/armedbear/lisp/Version.java
src/org/armedbear/lisp/abcl-contrib.lisp

rc14
TODO manual needs much description about pathnames

abcl 1.8.0 metadata

---

.github/workflows/abcl-test.yml

Final version of initial Github Actions workflow

GitHub/actions (#14)

---

src/org/armedbear/lisp/run-program.lisp

(reported by Eric Timmons)
Fixes <https://abcl.org/trac/ticket/480>

Fix SYS:PROCESS-PID with SYS:RUN-PROGRAM

---

src/org/armedbear/lisp/JarPathname.java
src/org/armedbear/lisp/Pathname.java
src/org/armedbear/lisp/ZipCache.java
src/org/armedbear/lisp/asdf.lisp
t/pathname.lisp

Fix zip cache to actually check modification date for nested zip archives

Easye/zip cache/20201129a

---

abcl-prove.asd
t/generic-method.lisp

Tests <https://abcl.org/trac/ticket/485>

Test for evaluation of incongruent generic keywords

---

src/org/armedbear/lisp/clos.lisp

Modifies lambda list for generic function defined through a defmethod to have only &key (but without arguments) when keyword arguments are specified, following CL standard.
This makes congruent to defmethod(s) defined when they are using keywords arguments
[https://abcl.org/trac/ticket/485](https://abcl.org/trac/ticket/485)

Proposal to fix https://abcl.org/trac/ticket/485 

---

examples/pure-lisp-to-java/Main.java

Seems to have been copied by mistake from lisp-to-java/Main.java

Remove confusing comment in example

---

src/org/armedbear/lisp/extensible-sequences.lisp

Addresses <https://github.com/armedbear/abcl/issues/363>.

Place :extensible-sequences in *features*

---

src/org/armedbear/lisp/extensible-sequences.lisp

@phoe suggested <https://github.com/armedbear/abcl/pull/364/files#r593767261>

Use PUSHNEW for *FEATURES*

---

src/org/armedbear/lisp/ComplexVector.java

Fixes #404 
- Updated fill pointer when an array is shrinked if fill pointer was
previously setted

Fix to print fill pointered array issue 

---

src/org/armedbear/lisp/Lisp.java

Fix (coerce 'documentation 'function) issue

---

src/org/armedbear/lisp/Lisp.java

Addresses <https://github.com/armedbear/abcl/issues/440>.

Clarify argument limits somewhat

---

src/org/armedbear/lisp/restart.lisp

Easye/undefined function restart/20220309e

---

doc/manual/abcl.bib

doc: update non-resolving reference to Rhode's extensible sequences

---

contrib/jss/javaparser.lisp
contrib/jss/read-sharp-quote-expression.lisp

Must be a change from updated javaparser. No idea how this worked with the patch I submitted. Breaks on #1"System.out"

getField->getName 

---

src/org/armedbear/lisp/disassemble.lisp

Easye/function class bytes/20220310a

---

src/org/armedbear/lisp/Pathname.java
src/org/armedbear/lisp/directory.lisp

Pathname directory wasn't handling . or .. in certain cases

---

ci/install-openjdk.bash

Further edits to URIs
tweak openjdk17

ci: update openjdk installations

---

.github/workflows/abcl-test.yml
README
abcl.rdf
build.xml
ci/create-abcl-properties.awk
ci/create-abcl-properties.bash
ci/install-openjdk.bash
doc/manual/abcl.tex
src/org/armedbear/lisp/LispThread.java
src/org/armedbear/lisp/Symbol.java

openjdk19 working with virtual threads

Virtual threading/20221202a

---

src/org/armedbear/lisp/compile-file-pathname.lisp

Fixes <https://github.com/armedbear/abcl/issues/494>
Supersedes <https://github.com/armedbear/abcl/pull/538>

Fix COMPILE-FILE-PATHNAME for Maxima

---

contrib/abcl-introspect/stacktrace.lisp

Sometimes finding the constructor for JavaStackFramefailed.  Most such references should be scoped anyhow.

abcl-introspect: scope JavaStackFrame reference

---

src/org/armedbear/lisp/run-program.lisp

(oldk1331)
Addresses <https://github.com/armedbear/abcl/issues/506>.

Fix SYS:RUN-PROGRAM waiting for exit

---

src/org/armedbear/lisp/run-program.lisp

Followup to
<https://github.com/armedbear/abcl/commit/1113f4f7778611d2568ddee3478255b976191fbe>.
Hopefully still resolves <https://github.com/armedbear/abcl/issues/506>

Further necessary triage for SYS:RUN-PROGRAM

---

Dockerfile

This was necessary to build under Debian Podman.

Qualify remote registry for containerization base

---

doc/manual/java.tex
src/org/armedbear/lisp/runtime-class.lisp

(Uthar)
Via <https://github.com/armedbear/abcl/pull/517#issuecomment-1444516133>.

Augment JAVA:JNEW-RUNTIME-CLASS docstring

---

ci/install-ansi-test.bash

See <https://gitlab.common-lisp.net/ansi-test/ansi-test/-/issues/31>.

ci: pin ANSI-TEST version

---

doc/packaging-abcl.org

doc: proofread ABCL-AIO

---

src/org/armedbear/lisp/subtypep.lisp

Thanks to the report by <https://github.com/hyotang666>.
Resolves <https://github.com/armedbear/abcl/issues/491>.

Implement MOP compound type specializer

---

src/org/armedbear/lisp/compiler-pass2.lisp
test/lisp/abcl/compiler-tests.lisp

Fix to issue when compiling literal quoted forms that share parts, fixes #606

Fix to issue when compiling literal quoted forms

---

src/org/armedbear/lisp/clos.lisp
test/lisp/abcl/clos-tests.lisp

[clos] Potential fix for issue on propagation off initargs 

---

src/org/armedbear/lisp/StandardObject.java
test/lisp/abcl/clos-tests.lisp

Fix for issue on update-instance-for-redefined-class generic function

---

src/org/armedbear/lisp/clos.lisp
test/lisp/abcl/clos-tests.lisp

Supersedes <https://github.com/armedbear/abcl/pull/632>.

[azf-fix-630] fixup for @alejandrozf CLOS propagation on existent instances

---

CHANGES
src/org/armedbear/lisp/GrayStream.java
src/org/armedbear/lisp/Lisp.java
src/org/armedbear/lisp/TwoWayStream.java
src/org/armedbear/lisp/gray-streams-java.lisp
src/org/armedbear/lisp/gray-streams.lisp

+ implement INTERACTIVE-STREAM-P
+ update CHANGES
+ use SUBTYPEP in coercion checkStream()

Further GRAY-STREAMS work 

---

src/org/armedbear/lisp/GrayStream.java
src/org/armedbear/lisp/gray-streams-java.lisp

Work in progress…
TODO
+ remove commented out code
+ see about not having to use the Java trampoline

gray-streams: use generic function directly in proxy

---

src/org/armedbear/lisp/gray-streams.lisp

Also remove the default method for [FUNDAMENTAL-BINARY-STREAM](https://github.com/yitzchak/nontrivial-gray-streams#fundamental-binary-stream) since this is supposed to be explicitly defined by binary streams.
Removing this method causes an infinite recursion which is the reason for the type checks on the default methods.

Gray: Add type checks to default methods to prevent recursion

---

build.xml
ci/create-abcl-properties.bash
ci/set-jdk.bash

Improve set-jdk.bash for better error handling.

ci: improvements for openjdk21 and beyond

---

.github/workflows/abcl-test.yml
ci/install-openjdk.bash
ci/set-jdk.bash

Deprecate openjdk22, switching to openjdk23.

ci: update openjdk installations; add openjdk23
