armedbear/abcl

contrib/abcl-introspect.lisp
contrib/abcl-introspect/abcl-introspect.asd
contrib/abcl-introspect/abcl-introspect.lisp
contrib/jss/collections.lisp
contrib/jss/invoke.lisp
src/org/armedbear/lisp/fdefinition.lisp
src/org/armedbear/lisp/print.lisp

The ABCL compiler stores constants that are used in function execution
as private java fields. This includes symbols used to invoke function,
locally-defined functions (such as via labels or flet) and string and
other literal constants.
This file provides access to those internal values, and uses them in
at least two ways. First, to annotate locally defined functions with
the top-level function they are defined within, and second to search
for callers of a give function(*). This may yield some false
positives, such as when a symbol that names a function is also used
for some other purpose. It can also have false negatives, as when a
function is inlined. Still, it's pretty useful. The second use to to
find source locations for frames in the debugger. If the source
location for a local …

ABCL Introspect - Support for new slime debugger functionality

---

abcl.properties.in
build.xml

For compiling beyond openjdk11, one needs to increment the values of
'abcl.javac.target' and 'abcl.javac.source' in <file:abcl.properties>.

build: make target JVM and source compatiblity developer configurable

---

src/org/armedbear/lisp/numbers.lisp
t/decode-float.lisp

(Robert Dodier)
Address problems with DECODE-FLOAT
Includes all known patches from Robert Dodier.
Robert Dodier
References
<https://github.com/armedbear/abcl/issues/93>
<https://github.com/armedbear/abcl/issues/94>
<https://github.com/armedbear/abcl/issues/95>
`rdfs:seeAlso` <https://gitlab.common-lisp.net/abcl/abcl/blob/master/src/org/armedbear/lisp/numbers.lisp>.

[IN PROGRESS] Fix the numeric tower for floats

---

src/org/armedbear/lisp/Bignum.java
src/org/armedbear/lisp/DoubleFloat.java
src/org/armedbear/lisp/Fixnum.java
src/org/armedbear/lisp/JavaObject.java
src/org/armedbear/lisp/LispCharacter.java
src/org/armedbear/lisp/SingleFloat.java

somewhat-functional-programmer contributes <https://mailman.common-lisp.net/pipermail/armedbear-devel/2019-December/004021.html>
I've looked into this issue at length now and I think I have something worth
discussing and potentially trying[0] . The root issue here lies in how ABCL
converts its CL representation of integers to Java, as well as its conversion
of Java primitives to other Java primitives.
ABCL's common superclass for all objects (LispObject) includes two methods to
convert the lisp object to a Java representation: LispObject.javaInstance() and
LispObject.javaInstance(Class). LispObject.javaInstance(Class) presumably tries
to convert the internal representation to the type represented by the Class
passed in. In practice, this seems to be primarily used for Java primitive …

Refit numeric tower in a systematic manner

---

t/compiler.lisp

Start ormalizing common form for problems in the compiler.
Additional failures reported by Paul Dietz in
<https://mailman.common-lisp.net/pipermail/armedbear-devel/2020-May/004054.html>
<https://mailman.common-lisp.net/pipermail/armedbear-devel/2020-May/004055.html>

t/compiler: add test failures reported by pdietz

---

ci/create-abcl-properties.awk
ci/create-abcl-properties.bash

Running the autoconfiguration script now sets both the target and
source options for the java compilation, selecting the maximum target
for compilation platform.

build: fix autoconfiguration script

---

src/org/armedbear/lisp/Bignum.java
src/org/armedbear/lisp/Lisp.java
t/byte-vectors.lisp

This should signal an error:
(make-array 16 :element-type '(unsigned-byte 32) :initial-element  (expt 2 32))

The upper limit for 32 bit values is simply wrong.

---

.travis.yml
ci/install-cl+ssl.bash
ci/test-cl+ssl.lisp
patches/cl-plus-ssl-abcl.patch

Update version of ci tested CL+SSL to use patch for openjdk14, and
update the local version of the patch under <file:patches/>.

ci: test CL+SSL

---

.travis.yml
ci/install-cffi.bash
patches/cffi-shareable-vectors.patch

Uses
<https://github.com/armedbear/cffi/tree/abcl/easye-shareable-byte-vector-20200530a>.

ci: use patched version CFFI that implements MAKE-SHAREABLE-BYTE-VECTOR

---

.travis.yml
ci/test-ironclad.lisp

This shakes down our vector implementation; showcases how slow
unoptimized-for-abcl IRONCLAD code can be.

ci: run the IRONCLAD tests

---

src/org/armedbear/lisp/FloatFunctions.java
src/org/armedbear/lisp/Ratio.java
src/org/armedbear/lisp/numbers.lisp
t/decode-float.lisp

DECODE-FLOAT now returns a significand in the interval between 1/2
(inclusive) and 1 (exclusive) as implied by ANSI.
Coercion of values smaller than 2^-1023 to double floats no longer
returns zero.
Completed addressing the issues raised by Robert Dodier in
<https://github.com/armedbear/abcl/issues/93>,
<https://github.com/armedbear/abcl/issues/94>, and
<https://github.com/armedbear/abcl/issues/95>.

Further fixes for floating point values

---

.travis.yml
ci/install-jeannie.bash
t/rdf.lisp

ABCL-PROVE now executes the new <file:t/rdf.lisp> test.
supersedes #229

ci: Use Jeannie to test <urn:abcl.org/**/*> namespace

---

ci/abcl-prove.lisp
ci/test-abcl-introspect.lisp
ci/test-abcl.lisp
ci/test-ansi.lisp
ci/test-cffi.lisp
ci/test-cl+ssl.lisp
ci/test-ironclad.lisp
ci/test-static-vectors.lisp

Fold QL:QUICKLOAD operations into lists (something I learned by
"reading" Twitter).
Housecleaning by removing unneeded references to testing packages to
load the ABCL ASDF definition.

ci: add TIME form for test invocations

---

abcl.asd
test/lisp/abcl/clos-tests.lisp
test/lisp/abcl/compiler-tests.lisp
test/lisp/abcl/package-local-nicknames-tests.lisp
test/lisp/abcl/package.lisp
test/lisp/abcl/pathname-tests.lisp
test/lisp/abcl/wild-pathnames.lisp

Restore loading under SBCL and CCL.
FIXME: package-local-nicknames-tests only runs once in the same
process, causing a mysterious failure on the second time.

Revisions for the long neglected ABCL/TEST/LISP suite

---

src/org/armedbear/lisp/ComplexArray_IntBuffer.java
src/org/armedbear/lisp/ComplexVector_IntBuffer.java
src/org/armedbear/lisp/Lisp.java
src/org/armedbear/lisp/SimpleArray_IntBuffer.java
src/org/armedbear/lisp/SimpleArray_UnsignedByte32.java
src/org/armedbear/lisp/make_array.java

GOAL: completely remove allocation of any UnsignedByte32 in
make_array.java.  Surprised that it mostly works this way…
Fix directAllocation in SimpleArray_CharBuffer.java
TODO: finish checking the directAllocation for types
TODO: finish refactoring lisp.coerce…method names

Further (INCOMPLETE) work on byte vectors

---

contrib/abcl-introspect/util.lisp

e.g.
(abcl-introspect/jvm/tools/javap:disassemble-class-bytes
(ext:read-class
"~//work/abcl/build/classes/org/armedbear/lisp/run_program_60.cls"))
TODO:  shorten into generic method

abcl-introspect: add convenience method to read class files

---

src/org/armedbear/lisp/BasicVector_ByteBuffer.java
src/org/armedbear/lisp/BasicVector_CharBuffer.java
src/org/armedbear/lisp/BasicVector_IntBuffer.java
src/org/armedbear/lisp/ComplexArray_ByteBuffer.java
src/org/armedbear/lisp/ComplexArray_IntBuffer.java
src/org/armedbear/lisp/ComplexVector_ByteBuffer.java
src/org/armedbear/lisp/ComplexVector_IntBuffer.java
src/org/armedbear/lisp/util/DecodingReader.java
src/org/armedbear/lisp/util/RandomAccessCharacterFile.java

Seemingly, the openjdk11 compiler optimizes the call to
java.nio.Buffer.flip() in to be directly on the java.nio.ByteBuffer
type.  We fixed other instances of java.nio.Buffer interfaces to the
point of being able to run the ANSI-TEST suite.
This caused errors such as:
Exception in thread "interpreter" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
at org.armedbear.lisp.util.DecodingReader.<init>(DecodingReader.java:87)
at org.armedbear.lisp.Stream.<init>(Stream.java:165)
at org.armedbear.lisp.Stream.<init>(Stream.java:148)

Fix running openjdk11 compilation on openjdk8

---

.gitignore
abcl.asd
build.xml
src/org/armedbear/lisp/ArgumentListProcessor.java
src/org/armedbear/lisp/Binding.java
src/org/armedbear/lisp/Closure.java
src/org/armedbear/lisp/ClosureBinding.java
src/org/armedbear/lisp/Environment.java
src/org/armedbear/lisp/Function.java
src/org/armedbear/lisp/FunctionBinding.java
src/org/armedbear/lisp/JavaObject.java
src/org/armedbear/lisp/MemoryClassLoader.java
src/org/armedbear/lisp/Pathname.java
src/org/armedbear/lisp/Primitives.java
test/lisp/abcl/closure-serialization.lisp
test/src/org/armedbear/lisp/serialization/SerializationTest.java

This implements serialization for functions:
- top-level and local
- interpreted and compiled
- closures included (provided closed-over objects are themselves serializable, of course)
Notable points worth a second look: I changed how loadedFrom is computed for functions loaded from FASLs, recording the fasl truename if present. Using *load-truename* only would break reading function class bytes for serialization (but also for disassembly).
A few (pretty minimal) tests are provided in Java and in Lisp.
What's missing:
- Test serialization/deserialization across ABCL images
- Inlcuding re-serializing a deserialized function on a different image (could depend from a FASL that doesn't exist on the receiving image/machine, we should simulate that in a test)
- Test serialization/deserialization …

Feature: serialization of functions

---

src/org/armedbear/lisp/compile-file.lisp

When compiling top-level DEFVAR/DEFPARAMETER/DEFCONSTANT forms for
specialized vectors, preserve type information by emitting
CL:MAKE-ARRAY calls.
Fixes <https://github.com/armedbear/abcl/issues/266>.

compiler: emit make-array for top-level specialized vector forms

---

src/org/armedbear/lisp/loop.lisp

(Daniel Kochmański)
Cribbed from
<https://gitlab.com/embeddable-common-lisp/ecl/-/merge_requests/226/diffs>:
Simple MAPCAR must be replaced by a slightly more complicated DO, because the
list may not be a proper list. I want to dedicate this ballad to myself.
This is a tale of a sorry quest
To master pure code at the T guru's behest
I enrolled in a class that appealing did seem
For it promised to teach fine things like T3 and Scheme
The first day went fine; we learned of cells
And symbols and lists and functions as well
Lisp I had mastered and excited was I
For to master T3 my hackstincts did cry
I sailed through the first week with no problems at all
And I even said "closure" instead of "function call"
Then said the master that ready were we
To start real hacking instead of simple theory …

Fix loop destructuring problems

---

.travis.yml
build.xml
ci/create-abcl-properties.bash
ci/install-adoptjdk.bash
src/org/armedbear/lisp/Lisp.java

Use openjdk15 as latest version instead of openjdk14 under Travis CI.
Allow for java.version that reports an integer without a patchlevel
which is needed for running openjdk15.

Patches and CI changes for running on openjdk15

---

src/org/armedbear/lisp/ComplexVector_ByteBuffer.java

Fixes ANSI test VECTOR-PUSH-EXTEND.26 which was broken in the overhaul
of specialized byte arrays.

Fix VECTOR-PUSH-EXTEND for (UNSIGNED-BYTE 8)

---

contrib/quicklisp/quicklisp-abcl.asd
contrib/quicklisp/quicklisp-abcl.lisp

Emit more verbosity to the stream designated by CL:*LOAD-VERBOSE*.
TODO: find a reproducible failing test case to ensure we have fixed
this.
Supersedes #295

quicklisp-abcl: remove all Quicklisp fasls on failure

---

abcl.properties.in
build.xml
ci/create-abcl-properties.awk
ci/create-abcl-properties.bash

(From a suggestion by Slyrus)
Replace use of abcl.javac.{source,target} with the "magic"
ant.build.javac,{source,target} properties.
Explicitly configure 'abcl.release' target to use openjdk8 compilation.
The Java compilation options are perhaps underspecified in terms of
the target JVM in order to support a developer who simply wants to
compile and run locally with least hassles.
When preparing ABCL binaries for wider distribution, the values of the
abcl.build.target.javac and abcl.build.source.java become more
important.
The 'abcl.properties.autoconfigure.*' targets use the
ci/create-build-properties.bash script to set these options for
various openjdk platforms.
* * *
build: build the wrapper with the release
N.b. the wrapper is a local artifact, not supposed to be shipped with
the …

build: make building and running a local ABCL easier

---

src/org/armedbear/lisp/java/swing/REPLConsole.java

Apparently needed for the FreeBSD version of openjdk15.

Explicitly scope java.lang.Thread.yield() invocation

---

src/org/armedbear/lisp/ComplexVector_ByteBuffer.java

This bug was preventing zs3 from being loading.

Fix adjusting non-simple (unsigned-byte 8) vectors

---

src/org/armedbear/lisp/compile-file-pathname.lisp

(Robert Munyer)
Fixes "Wrong file type returned by COMPILE-FILE-PATHNAME" (ticket
#476) and "COMPILE-FILE, COMPILE-FILE-PATHNAME disagree on output dir"
(not yet ticketed).
<https://abcl.org/trac/ticket/476>
<https://mailman.common-lisp.net/pipermail/armedbear-devel/2020-November/004162.html>

New algorithim for COMPILE-FILE-PATHNAME

---

src/org/armedbear/lisp/BasicVector_ByteBuffer.java
src/org/armedbear/lisp/ComplexArray_ByteBuffer.java
src/org/armedbear/lisp/ComplexVector_ByteBuffer.java
src/org/armedbear/lisp/ComplexVector_IntBuffer.java

The position of all buffers should always be zero.  TODO how to
unintrusively make this assertion?
We fix new types specializing (or (unsigned-byte 8) (unsigned-byte
32)) in BasicVector_ByteBuffer, ComplexArray_ByteBuffer,
ComplexVector_ByteBuffer, and ComplexVector_IntBuffer for relative
accesses which always advance the position of the
underlying java.nio.Buffer subclass.
Fixes <https://github.com/armedbear/abcl/issues/345>.

arrays: fix fail to reset position after relative access

---

build.xml
ci/create-abcl-properties.bash

Add support for configuring openjdk6, openjdk7, and openjdk16 within
CI via adding targets for Ant.
TODO: macroize this stuff in Ant to add all supported platforms.  But
we now at least configure the ones we (sorta) actively test.

build: add configuration targets more openjdks

---

src/org/armedbear/lisp/Lisp.java
src/org/armedbear/lisp/LispThread.java
src/org/armedbear/lisp/Symbol.java

Thanks to no-defun-allowed for clueing me into that this would be
somewhat easily done.
When the underlying JVM supports virtual threads, :VIRTUAL-THREADS
will be present in CL:&ast;FEATURES&ast;.
The special variable THREADS:&ast;THREADING-MODEL&ast; contains the type of
threads being spawned by the implementation: it will be :NATIVE for
the default, which is usually a one-to-one mapping from each Java
thread to a native thread, and will be :VIRTUAL if using the
lightweight threads present in Project Loom JVMs.
Tested on "OpenJDK_64-Bit_Server_VM-Oracle_Corporation-16-loom+9-316".
Netbeans 12.2 has problems running the debugger with this change due
to some sort of bad interaction with the JDWP protocol.
Project Loom documentation of java.lang.Thread …

Support use of Project Loom virtual threads

---

src/org/armedbear/lisp/RandomState.java
src/org/armedbear/lisp/Symbol.java

Not a particularly nice byte vector representation though, but it gets the job done:
```
CL-USER> (write (make-random-state))
#<RANDOM-STATE {301D7DA5}>
CL-USER> (write (make-random-state) :readably T)
#.(SYSTEM::READ-RANDOM-STATE #(-84 -19 ... -69 39 120))
CL-USER> (setf *read-eval* NIL)
NIL
CL-USER> (let ((*read-eval* NIL)) (write (make-random-state) :readably T))
#<RANDOM-STATE {3B023252}> cannot be printed readably.
[Condition of type PRINT-NOT-READABLE]
...
```
[From CLHS](http://clhs.lisp.se/Body/v_pr_rda.htm):
> If `*read-eval*` is false and `*print-readably*` is true, any such method that would output a reference to the ``#.'' reader macro will either output something else or will signal an error (as described above).
Based on that this should be conforming and users will not be …

Fix printing of `RANDOM-STATE`.

---

src/org/armedbear/lisp/Lisp.java

Noticed `:|aarch64|` on `*features*` when running on ARM64.

Uppercase arch before pushing it to *features*

---

src/org/armedbear/lisp/dribble.lisp

Fixes #407 
A  fix/improvement to cl:dribble
This version save almost everything to the specified file
creating a new internal REPL for dribbling and also ends smoothly
when _(dribble)_ is called

- Proposal to fix https://github.com/armedbear/abcl/issues/407

---

src/org/armedbear/lisp/Bignum.java
src/org/armedbear/lisp/Fixnum.java
src/org/armedbear/lisp/Lisp.java
src/org/armedbear/lisp/Ratio.java

Fixes #177 
- Filled slots 'operation' and 'operands' of DivisionByZero condition when it is raised

Proposal to fix Github issue #177 

---

src/org/armedbear/lisp/clos.lisp
src/org/armedbear/lisp/precompiler.lisp
src/org/armedbear/lisp/psetf.lisp

Unlike SBCL or CCL, ABCL doesn't have a SIMPLE-PROGRAM-ERROR
condition.  Presumably these inadvertent references were present in
patches adapted from those implementations.
Supersedes #451, #452, and #453

Remove inadvertent references to SIMPLE-PROGRAM-ERROR

---

src/org/armedbear/lisp/java.lisp
test/lisp/abcl/runtime-class.lisp

related ticket: 
fix #470 
This prevents `jclass-superclass` from failing on names (keywords) of classes generated by `jnew-runtime-class` (it fails because they are created in a different ClassLoader and it can't find them). By passing an actual Class it doesn't have to do a lookup by name. The fail occured on the first iteration of the loop in `print-java-object-by-class`. 
NB: Yes, `jcall` works on keywords. So this is working code:
```
(jcall "getName" :|java.util.List|)
(jclass-superclass :|java.util.HashMap|)
```
The inheritance mechanism of `print-java-object-by-class` is unchanged, because it internally converts the classes found by `jclass-superclass` into a keyword in order to `find-method`. Before this change, it also worked because of the above fact that `jcall getName` works …

Start out with the actual Class in print-object on java:java-object

---

src/org/armedbear/lisp/compile-file.lisp

Additional work superseding <https://github.com/armedbear/abcl/pull/488>: 
- re-worked compiler diagnostic machinery a bit to be more useful 
- emit diagnostic when compiler falls back to interpreted forms

Alejandrozf/azf fix compilation long sexps/20220517a

---

src/org/armedbear/lisp/Extensions.java
src/org/armedbear/lisp/Lisp.java
src/org/armedbear/lisp/LispThread.java

What happens on interrupt
-------------------------
I'm assuming there's both a worker thread(w) and a control thread(c) running.
Running in thread(c)
Call (interrupt-thread thread(w) function args)
thread(c).interruptThread unpacks the arguments into a list
It then calls thread(w).interrupt(function, args)
thread(w).interrupt pushes args and fun on thread(w) thread local variable pending
it then call java's interrupt() method.
If things are left alone, the java interrupt mechanism will at some
point throw an InterruptedException when running inside thread(w) various
lispThread functions catch the InterruptedException and call
processThreadInterrupts()
processThreadInterrupts() then runs the functions in the thread local
variable pending.
There's also one check that uses the java …

This commit makes interrupt-thread react quickly.

---

src/org/armedbear/lisp/clos.lisp

The patch lets finalize-inheritence run even if a class is already finalized despite what the ABCL source says the AMOP says.

See https://github.com/armedbear/abcl/issues/465

---

pom.xml

The basic assembly of <file:dist/abcl.jar> now works, although these
aren't completely hooked up to Maven's notion of output artifacts.
TODO:
We aren't really intercepting maven-jar-plugin default-jar goal
correctly, so the resulting <file:build/abcl-1.6.x-SNAPSHOT.jar>
artifact doesn't contain all artifacts.  We probably need to correctly
define our resources to Maven, but they are currently expressed as
various Ant properties, so we need to slave the Maven goals to
appropiate Ant tasks?
Maven really wants to create all output under a single directory,
while the Ant recipe puts intermediate artifacts under <file:build/>
and final results in <file:dist/>.
Need to somehow encapsulate the existence of
<file:dist/abcl-contrib.jar> within the <file:contrib/pom.xml> Maven
description, even …

build: can now use Maven to build

---

src/org/armedbear/lisp/jvm-instructions.lisp
t/compiler.lisp

Starts to fix the CFFI tests, which used to fail complaining about not be able to compile a JVM `ASTORE` form.  Now, other things fail, and the test cores, but perhaps that is progress.

Compiler wide/20221208a

---

ci/create-abcl-properties.bash

Need at least these for the CL+SSL CFFI linkages to work.

build: autoconfigure with common --add-opens for openjdk17+

---

README
build.xml
contrib/pom.xml
pom.xml

No longer needing to support openjdk6 enables us to use the Maven Ant run plugin to delegate common Maven lifecycle points to the canonical build instructions.
The following Maven invocation now work:
mvn compile
mvn install
mvn test
Tests via ANSI-TEST and CL-BENCH still need to be cloned locally manually in order for the full testing suite to pass.
Maven will install Ant "on its own" if it isn't already present.

build:  Maven now abcl to build and test ABCL

---

src/org/armedbear/lisp/format.lisp
test/lisp/abcl/misc-tests.lisp

(Tarn W. Burton) <https://github.com/yitzchak>
Simple LOOP requires only compound forms. Hence NIL is not permitted. Some FORMAT directives (like newline) return NIL as the form when they have nothing to add to the body. Normally this is fine since BLOCK accepts NIL as a form. On the other hand, when the newline directive is inside of an iteration directive this will produce something like
(LOOP (fu) nil (bar))
This is probably mostly a spec compliance issue. It does not show up as a bug since ABCL's Loop implementation isn't strict in this sense. Loading an alternate LOOP implementation which is more strict like Khazern will cause FORMAT to fail.
PRs have already been submitted and merged for some of the other CMUCL-based FORMAT implementations like Clasp and ECL.
Via …

Avoid NIL in simple LOOP from FORMAT directives

---

contrib/abcl-asdf/README.markdown
contrib/abcl-asdf/maven.lisp
contrib/abcl-asdf/package.lisp

Not as useful as one might think, as ASDF apparently swallows all conditions.

abcl-asdf: provide restart for installing Maven

---

src/org/armedbear/lisp/MathFunctions.java

A previous commit would return `Fixnum.ZERO` for `(log b n)` if `b` is zero; this commit makes it return `b * n`, that will automatically return the correct zero (`0`, `0.0` or `0.0d0`), according to the inexactness contagion rules.
(Sorry for having missed this in the other PR)

Return 0 with appropriate inexactness from log

---

src/org/armedbear/lisp/BroadcastStream.java
src/org/armedbear/lisp/BuiltInClass.java
src/org/armedbear/lisp/CLOSProxyStream.java
src/org/armedbear/lisp/ConcatenatedStream.java
src/org/armedbear/lisp/EchoStream.java
src/org/armedbear/lisp/Lisp.java
src/org/armedbear/lisp/Stream.java
src/org/armedbear/lisp/StructureObject.java
src/org/armedbear/lisp/Symbol.java
src/org/armedbear/lisp/TwoWayStream.java
t/gray-streams.lisp

The stupidest implementation possible for <https://github.com/armedbear/abcl/issues/512>: create an intermediate CLOSProxyStream object, have Lisp.checkStream() return this proxy when passed a CLOS object whose type predicate machinery indicates it is descended from STREAM.
See how this does with the test suites.

Gray streams/GitHub/issue/512

---

src/org/armedbear/lisp/gray-streams.lisp

(Uthar)
Addresses <https://github.com/armedbear/abcl/issues/511>.

Fix gray-stream-element-type missing for binary streams

---

contrib/posix-syscalls/getenv.lisp
contrib/posix-syscalls/package.lisp
contrib/posix-syscalls/posix-syscalls.asd
contrib/posix-syscalls/posix-syscalls.org
contrib/posix-syscalls/system.lisp
doc/manual/abcl.tex

Based on code provided by Alan Ruttenberg in
<https://github.com/alanruttenberg/lsw2/blob/owlapiv4/util/setenv.lisp>.
See
<https://mailman.common-lisp.net/pipermail/armedbear-devel/2023-April/004308.html> ff.
See <file:contrib/posix-syscalls/posix-syscalls.org>.

Create POSIX-SYSCALLS contrib to set environment variables

---

contrib/abcl-stepper/README.markdown
contrib/abcl-stepper/abcl-stepper.asd
contrib/abcl-stepper/abcl-stepper.lisp
src/org/armedbear/lisp/Environment.java
src/org/armedbear/lisp/Lisp.java
src/org/armedbear/lisp/step.lisp

This PR was made on top of PR [568](https://github.com/armedbear/abcl/pull/568) and brings to the table the possibility to run the stepper also inside the main REPL in Slime :100: ! (tested on Slime commit 50d4a7b1). 
It is also rebased with the latest changes in ABCL from master branch.
Other possible strategies for implementation <<https://github.com/armedbear/abcl/issues/264>>.

ABCL-STEPPER:  implementation of CL:STEP for interpreted code

---

contrib/abcl-introspect/README.org
contrib/abcl-introspect/procyon.lisp

- This makes procyon disassembler work in ABCL, internally it is using a temp file for the byte array received, then the temp file is passed to the decompiler.
- Updated decompiler status info
See #423

Fix for procyon decompiler (for cl:disassemble)

---

src/org/armedbear/lisp/Primitives.java

(Alan Ruttenberg)
<https://github.com/mnepveu> reported issues with using circular lists in ABCL with data structures for an application which works in SBCL/CCL but would cause ABCL to hang.
The following test case no longer causes ABCL to hang:
(setq *print-circle* t)
(defun number-of-items (rtype datefrom dateto)
10)
(defun circularlist (items)
(setf (cdr (last items)) items)
items)
(mapcar #'number-of-items
'("abîmé" "administratif" "autre" "client insatisfait" "coin défecteux"
"couleur / profil" "défectueux" "erreur créaction" "erreur du client"
"erreur expédition" "impression" "mesure" "offset" "qualité" "transport"
"égratignée")
(circularlist (list "2023-07-31"))
(circularlist (list "2023-08-07")))
Implementation from
<https://github.com/armedbear/abcl/issues/612#issuecomment-1667066 …

Fix MAPC/MAPCAR for circular lists

---

src/org/armedbear/lisp/Stream.java

Without this, #b/#o/#x/#r reader macros bomb out in Java making for a substandard user experience.

Signal error for malformed #b/#o/#x/#r reader macros

---

src/org/armedbear/lisp/Lisp.java

Addresses <https://github.com/armedbear/abcl/issues/508>.

Implement UPGRADED-ARRAY-ELEMENT-TYPE for non-specialized byte types

---

src/org/armedbear/lisp/AbstractVector.java
src/org/armedbear/lisp/BasicVector_ByteBuffer.java
src/org/armedbear/lisp/BasicVector_CharBuffer.java
src/org/armedbear/lisp/BasicVector_IntBuffer.java
src/org/armedbear/lisp/BasicVector_UnsignedByte16.java
src/org/armedbear/lisp/BasicVector_UnsignedByte32.java
src/org/armedbear/lisp/BasicVector_UnsignedByte8.java
src/org/armedbear/lisp/Primitives.java
src/org/armedbear/lisp/SimpleString.java
src/org/armedbear/lisp/SimpleVector.java
src/org/armedbear/lisp/replace.lisp

This patch turns vector-to-vector `replace` into a primitive with very fast copies between sequences of the same underlying types (and a slightly faster fallback in Java, although this is primarily for convenience). The current `(setf aref)` loop implementation is very slow, especially for ub8 vectors; code that stitches byte buffers together currently spends a lot of time in `replace` in my experience and a 100MB copy that currently takes ~75s takes ~35ms after this patch.
I'm not too familiar with the ABCL codebase, so some things probably still have to be fixed up. I'm especially unsure whether it's fine to do all the error checking in the primitive and leave the underlying methods unguarded. I'll be in `#abcl` for a while if things are more convenient that way.

Implement vector-to-vector `replace` as a primitive

---

src/org/armedbear/lisp/compiler-pass2.lisp
test/lisp/abcl/compiler-tests.lisp

Fixes #622: restrict in the validation to detect nested quoted forms that share components with previous externalized objects  so that now it only accepts exactly '#1#, ''#1#, and so on ...

Fix to fix to #606

---

Dockerfile

`openjdk` has been deprecated in favor of `eclipse-temurin`.
<https://hub.docker.com/_/eclipse-temurin>

container: use eclipse-temurin as base

---

src/org/armedbear/lisp/gray-streams.lisp

Some small tweaks.
- stream-terpri should return NIL not the newline character.
- stream-read-char-no-hang should have a default method. The implementation is not shown in the [Gray stream protocol](http://www.nhplace.com/kent/CL/Issues/stream-definition-by-user.html) example, but the existence of the default method is mentioned in the description for the generic.

Fix some Gray stream default methods

---

CHANGES
src/org/armedbear/lisp/gray-streams.lisp

[READ-LINE](https://novaspec.org/cl/f_read-line) should always return a second value indicating EOF as per the spec. If `eof-error-p` is NIL then the return should be `(values eof-value T)`. I checked CCL, CLASP, ECL, CMUCL and SBCL and this is in fact what they do.

Fix gray-read-line return

---

src/org/armedbear/lisp/Lisp.java
src/org/armedbear/lisp/gray-streams.lisp

Using `(typep obj 'stream)` effectively makes the generic function STREAMP not very useful since all streams need to subclass STREAM, which always returns T for STREAMP. This is an optional part of the Gray stream protocol. Some implementations enforce the requirement that streams must subclass STREAM, i.e. CMUCL, SBCL and CLISP. On the other hand Clasp, ECL, MKCL, Mezzano and CCL all implement the generic STREAMP and don't require that Gray streams subclass STREAM.

Use STREAMP to determine Gray stream API availability

---

CHANGES
src/org/armedbear/lisp/gray-streams.lisp

1. Generic versions of [TRUENAME and PATHNAME](https://github.com/yitzchak/nontrivial-gray-streams#pathname). This is an optional part of the original Gray stream proposal. 
2. [SETF STREAM-ELEMENT-TYPE](https://github.com/yitzchak/nontrivial-gray-streams#SETF-STREAM-ELEMENT-TYPE). This allows basic bivalent Gray streams. CCL already had this and I've added it to Clasp recently.
I've tested both of these in my test suite. I'll push an update to CHANGES once CI finishes just in case I have broken something else.

Add some more Gray extensions

---

src/org/armedbear/lisp/FileStream.java
src/org/armedbear/lisp/GrayStream.java
src/org/armedbear/lisp/JarStream.java
src/org/armedbear/lisp/Lisp.java
src/org/armedbear/lisp/Stream.java
src/org/armedbear/lisp/URLStream.java
src/org/armedbear/lisp/gray-streams-java.lisp

It appears #650 is not quite sufficient for PATHNAME. The spec states that PATHNAME-TYPE, PATHNAME-HOST, etc, should work after [close](https://novaspec.org/cl/f_close). This means that `coerceToPathname` will need to call the generic PATHNAME. To accomplish this I've added `getPathname` to the Stream class.
I've made this a draft because I haven't finished writing tests yet and I haven't verified that TRUENAME works in all cases.

Have coerceToPathname use Gray stream PATHNAME generic

---

src/org/armedbear/lisp/GrayStream.java
src/org/armedbear/lisp/gray-streams-java.lisp
src/org/armedbear/lisp/gray-streams.lisp

Add generic `STREAM-EXTERNAL-FORMAT`, `(SETF STREAM-EXTERNAL-FORMAT)` and support for implementing `CL:FILE-STRING-LENGTH`. Also add the Java side _clearInput and _setFilePosition.

Add more support for bivalent Gray streams

---

.github/workflows/abcl-test.yml
ci/ensure-jenv-is-present.bash
ci/install-ant.bash
ci/install-jenv.bash
ci/install-openjdk.bash
ci/set-jdk.bash

Robustify syntax for specifying operating system and architecture.

ci: update openjdk installations to latest

---

src/org/armedbear/lisp/Pathname.java
t/namestring.lisp

Test for failure; no implementation.
c.f. <https://github.com/armedbear/abcl/issues/656>

PARSE-NAMESTRING fails to explicitly denote current directory

---

src/org/armedbear/lisp/jvm-instructions.lisp
src/org/armedbear/lisp/runtime-class.lisp
test/lisp/abcl/runtime-class.lisp

I followed the instructions in https://abcl.org/contributing.shtml:
ant test.ansi.interpreted: `58 failures with 58 unexpected failures and 0 unexpected successes out of 21911 tests.`
ant test.ansi.compiled: `63 failures with 63 unexpected failures and 0 unexpected successes out of 21911 tests.`
both before and after.
I also ran ant test.abcl:
`20 out of 621 total tests failed`
after (it was 620 before).
I'm happy to make any changes you recommend.  Thanks!

JNEW-RUNTIME-CLASS: support passing and returning doubles in methods

---

build.xml
ci/create-abcl-properties.bash

Add opens for java.base/java.lang to ALL-UNNAMED observed as necessary for openjdk21 to introspect available threading models.
Fix broken alternate syntax.
Add openjdk23.

build: fix and update autoconfigure mechanism
